services:
  - type: web
    name: poker-analyzer-backend
    env: python
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false  # This will be set manually in Render dashboard
    autoDeploy: true
    branch: main
    rootDir: .
    plan: free