image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Environment
    init: |
      pip install -r requirements.txt
      python setup_test_env.py
      echo "✅ 환경 설정 완료!"
    command: |
      echo "🚀 포커 MAM 시작 중..."
      python run_poker_app.py

ports:
  - port: 5000
    onOpen: notify
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false