name: Daily Poker Trend Analysis

on:
  schedule:
    # 평일 오전 10시 실행 (UTC 1:00 = KST 10:00)
    # 월-금요일만 실행
    - cron: '0 1 * * 1-5'
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  TZ: Asia/Seoul

jobs:
  daily-trend-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-generativeai requests pandas numpy python-dateutil pytz
        
    - name: Verify environment
      run: |
        echo "Current time (KST): $(date)"
        echo "Python version: $(python --version)"
        echo "Running on: ${{ runner.os }}"
        
    - name: Collect YouTube Data
      id: collect
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        DEBUG_MODE: ${{ github.event.inputs.debug_mode || 'false' }}
      run: |
        cd backend/data-collector
        python scripts/youtube_trend_webhook_enhanced.py
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: daily-report-${{ github.run_number }}
        path: |
          backend/data-collector/reports/
          backend/data-collector/logs/
        retention-days: 30
        
    - name: Notify on failure
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-Type: application/json' \
          -d '{
            "text": "⚠️ 포커 트렌드 일일 분석 실패",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*⚠️ 포커 트렌드 일일 분석 실패*\n\n• 실행 시간: '"$(date)"'\n• 워크플로우: '"${{ github.workflow }}"'\n• 실행 번호: #'"${{ github.run_number }}"'\n• <'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'|상세 로그 확인>"
                }
              }
            ]
          }'