name: Daily Poker Trends

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 UTC 01:00 (KST 10:00)
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Get code
      uses: actions/checkout@main
      
    - name: Python setup
      uses: actions/setup-python@main
      with:
        python-version: '3.11'
        
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client==2.110.0
        pip install slack-sdk==3.26.1
        pip install requests==2.31.0
        pip install python-dotenv==1.0.0
        
    - name: Execute
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
      run: |
        echo "Starting analysis..."
        cd backend/data-collector
        
        # 디렉토리 생성
        mkdir -p scripts/logs
        mkdir -p scripts/reports
        
        # 테스트 모드 확인
        if [ "$TEST_MODE" = "true" ]; then
          echo "Running in test mode..."
          python scripts/simple_test.py
        else
          echo "Running full analysis..."
          python scripts/run_youtube_analysis.py
        fi
        
        echo "Analysis completed!"
        
    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Error logs ==="
        if [ -d "backend/data-collector/scripts/logs" ]; then
          find backend/data-collector/scripts/logs -name "*.log" -exec tail -n 100 {} \;
        fi