name: Poker Trends

on:
  schedule:
    # 매일 한국 시간 오전 10시 (UTC 01:00)
    - cron: '0 1 * * *'
  
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend/data-collector
        pip install google-api-python-client slack-sdk requests python-dotenv

    - name: Run analysis
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cd backend/data-collector
        python scripts/run_youtube_analysis.py || echo "Analysis failed with exit code $?"

    - name: Check logs
      if: always()
      run: |
        cd backend/data-collector
        if [ -d "scripts/logs" ]; then
          echo "=== Logs ==="
          tail -n 50 scripts/logs/*.log || echo "No logs found"
        fi