name: Test Environment

on:
  workflow_dispatch:

jobs:
  test-env:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install minimal dependencies
      run: |
        cd backend/data-collector
        pip install --upgrade pip
        pip install -r requirements-minimal.txt

    - name: Test environment
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cd backend/data-collector
        python scripts/test_env.py
        
    - name: List directory structure
      run: |
        echo "=== Directory Structure ==="
        ls -la backend/data-collector/
        ls -la backend/data-collector/scripts/
        
    - name: Test YouTube API
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        cd backend/data-collector
        python -c "
import os
from googleapiclient.discovery import build
api_key = os.getenv('YOUTUBE_API_KEY')
if api_key:
    print(f'API Key length: {len(api_key)}')
    try:
        youtube = build('youtube', 'v3', developerKey=api_key)
        print('✓ YouTube API client created successfully')
    except Exception as e:
        print(f'✗ YouTube API error: {e}')
else:
    print('✗ YOUTUBE_API_KEY not set')
"