name: YouTube Trends Webhook

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 UTC 01:00 (KST 10:00)
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install google-api-python-client requests
        
    - name: Run YouTube Trend Analysis
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        cd backend/data-collector
        python scripts/youtube_trend_webhook.py
        
    - name: Gemini Analysis (Future)
      if: false  # 향후 구현 예정
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "Gemini API integration coming soon..."